trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - v*

pool:
  vmImage: ubuntu-latest

stages:

# Detect Branch
- stage: DetectBranch
  jobs:
  - job: Detect
    steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        BRANCH=$(git branch -r --contains $(Build.SourceVersion) | head -n 1)
        echo "Branch: $BRANCH"
        echo "##vso[task.setvariable variable=tagBranch;isOutput=true]$BRANCH"
      name: detectStep

# DEV
- stage: DEV
  dependsOn: DetectBranch
  condition: contains(stageDependencies.DetectBranch.Detect.outputs['Detect.detectStep.tagBranch'], 'feature')
  jobs:
  - deployment: DevDeploy
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploy to DEV"